function geminiBTCUSD1hr = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GEMINIBTCUSD1HR = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GEMINIBTCUSD1HR = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  geminiBTCUSD1hr = importfile("H:\OneDrive - Universitaet Bern\02_Study\UniBern\21FS\Bachelor\Raw Data fro Gemini\gemini_BTCUSD_1hr.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jul-2021 16:13:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["UnixTimestamp", "Date", "Symbol", "Open", "High", "Low", "Close", "Volume"];
opts.VariableTypes = ["double", "datetime", "categorical", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Symbol", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
geminiBTCUSD1hr = flip(readtable(filename, opts));

end